---
title: "Summary Graphs of NUTR630 Intake"
author: "Dave Bridges, Liv Anderson and Rina Hisamatsu"
date: "2017-09-03"
output:
  pdf_document:
    highlight: tango
    keep_tex: yes
    number_sections: no
    toc: yes
---

```{r global_options, include=FALSE}
library(knitr)
#figures makde will go to directory called figures, will make them as both png and pdf files 
opts_chunk$set(fig.path='figures/',
               echo=TRUE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
options(scipen = 2, digits = 3)
# set echo and message to TRUE if you want to display code blocks and code output respectively

knitr::knit_hooks$set(inline = function(x) {
  knitr:::format_sci(x, 'md')
})


superpose.eb <- function (x, y, ebl, ebu = ebl, length = 0.08, ...)
  arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3,
  length = length, ...)

  
se <- function(x) sd(x, na.rm=T)/sqrt(length(x))

#load these packages, nearly always needed
library(tidyr)
library(dplyr)

# sets maize and blue color scheme
color.scheme <- c('#00274c', '#ffcb05')
```


```{r data-input}
library(readr)
filename <- 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQI-b1A4Zd-gx3FuY3lkKbWE0zKUfmAhpFovKOxow5AC1wWQpBsSvOKI0_gtZ4DJu5sj-YM1_1nsKUe/pub?gid=1032535237&single=true&output=csv'
data <- read_csv(filename)
```

These data can be found in `r getwd()` in a file named `r filename`.  This script was most recently updated on `r date()`.

# Analysis

## What Majors

```{r majors-summary}
library(forcats)
#grouped with most common 4

count.majors <-
  data %>%
  mutate(`Which discipline most closely matches your undergraduate degree?` = fct_lump(as.factor(data$`Which discipline most closely matches your undergraduate degree?`), n=4)) %>%
  group_by(`Which discipline most closely matches your undergraduate degree?`) %>%
  count() %>%
  arrange(desc(n)) %>%
  ungroup() %>%
  mutate(`Which discipline most closely matches your undergraduate degree?` = fct_recode(`Which discipline most closely matches your undergraduate degree?`, "Neuroscience" = "Psychology-related (Psychology, Neuroscience, etc.)")) 
  
par(mar=c(9,4,4,2))
with(count.majors, barplot(n,
                          las=2,
                          main="What is your major?",
                          col=color.scheme,
                          names.arg=`Which discipline most closely matches your undergraduate degree?`))
```
  
  
## What Topics are Students Interested In?

```{r student-interests}
library(sjPlot)

student.interest.data <- 
  data %>%
  select(starts_with('Macronutrient'),starts_with("Comprehensive"))


#manually ensured all columns have same levels
mylevels <- c('1','2','3','4','5')
student.interest.data.levels <-
  student.interest.data

student.interest.data.levels$`Macronutrient biochemistry is of interest to me.` <- factor(student.interest.data.levels$`Macronutrient biochemistry is of interest to me.`, levels=mylevels)

student.interest.data.levels$`Macronutrient biochemistry is important for my career interests.` <- factor(student.interest.data.levels$`Macronutrient biochemistry is important for my career interests.`, levels=mylevels)

student.interest.data.levels$`Comprehensive understanding of the digestive tract is of interest to me.` <- factor(student.interest.data.levels$`Comprehensive understanding of the digestive tract is of interest to me.`, levels=mylevels)

student.interest.data.levels$`Comprehensive understanding of the digestive tract is important for my career interests.` <- factor(student.interest.data.levels$`Comprehensive understanding of the digestive tract is important for my career interests.`, levels=mylevels)

sjp.likert(student.interest.data.levels,
           sort.frq='neg.asc',
           values='hide',
           show.legend=FALSE,
           show.n=FALSE)
```

## Learning Assessment

```{r learning-assessment}

student.assessment.data <- 
  data %>%
  select(starts_with("What is your level of agreement on the following statements?"))

library(stringr)
colnames(student.assessment.data) <- str_sub(colnames(student.assessment.data), 63, -2)

#manually ensured all columns have same levels
mylevels <- c('Strongly Agree','Agree','Neutral','Disagree','Strongly Disagree')

student.assessment.data$`When a difficult assignment is given to me, I feel confident that I can complete it.` <- factor(student.assessment.data$`When a difficult assignment is given to me, I feel confident that I can complete it.`, levels=mylevels)

student.assessment.data$`When given an assignment to complete, I produce better outcomes with a community of support (i.e., instructor or peer support).` <- factor(student.assessment.data$`When given an assignment to complete, I produce better outcomes with a community of support (i.e., instructor or peer support).`, levels=mylevels)

student.assessment.data$`I am aware of the skills I develop when I complete different types of assignments.` <- factor(student.assessment.data$`I am aware of the skills I develop when I complete different types of assignments.`, levels=mylevels)

student.assessment.data$`I am motivated to complete an assignment if I enjoy doing it.` <- factor(student.assessment.data$`I am motivated to complete an assignment if I enjoy doing it.`, levels=mylevels)

student.assessment.data$`I learn more through completing an assignment that I enjoy.` <- factor(student.assessment.data$`I learn more through completing an assignment that I enjoy.`, levels=mylevels)

student.assessment.data$`I perform better when completing an assignment that I enjoy (i.e., get a better grade).` <- factor(student.assessment.data$`I perform better when completing an assignment that I enjoy (i.e., get a better grade).`, levels=mylevels)


sjp.likert(student.assessment.data,
           values='hide',
           show.n=FALSE)
```

# GradeCraft Familiarity

```{r gradecraft}
gradecraft <- 
  data %>%
  group_by(`Are you familiar with GradeCraft?`) %>%
  count()

with(gradecraft, barplot(n,
                          las=1,
                          ylab="Responses",
                          main="Are you familiar with GradeCraft?",
                          col=color.scheme,
                          names.arg=`Are you familiar with GradeCraft?`))
```

Only `r gradecraft$n[2]` out of `r gradecraft$n[2]+gradecraft$n[1]` students were familiar with GradeCraft.

# Session Information

```{r session-information, echo=T}
sessionInfo()
```